import express from "express";
import { processApiEvents } from "./eventService.js";

import { persistApiEventResult } from "./eventPersistence.js";
import {
  getCanonicalEventByIdempotencyKey,
  listReconciliationRuns,
  getReconciliationRun,
  getCurrentAssetState,
  getAssetEventHistory,
  listExceptionCases,
  getRawRecords,
  getCanonicalEvents,
  getEventDecisions,
  getAssetStates,
  getExceptionCases,
  getReportArtifacts,
  resolveExceptionCase,
  insertApiUsageRecord,
} from "../persistence/repository.js";
import {
  registerWebhook,
  dispatchToMatchingWebhooks,
} from "./webhookService.js";
import { buildExceptionQueue } from "../reconciliation/exceptionQueue.js";
import { applyAutoResolution } from "../reconciliation/autoResolution.js";
import { canResolveException } from "./exceptionAuthorization.js";
/**
 * Creates the Express application used by the Week 7 API layer.
 *
 * The API receives the inventory baseline and policy as dependencies.
 * This keeps the API layer independent from file-loading concerns and
 * allows the same reconciliation components to be reused by tests.
 */
export function createApiServer({
  inventoryRawRecords = [],
  policy = null,
} = {}) {
  const app = express();

  // Parse JSON request bodies.
  app.use(express.json());

  // Capture API usage metrics for reporting.
  app.use((req, res, next) => {
    const startedAt = process.hrtime.bigint();

    res.on("finish", async () => {
      const elapsedMs =
        Number(process.hrtime.bigint() - startedAt) / 1_000_000;

      try {
        await insertApiUsageRecord({
          method: req.method,
          endpoint: req.path,
          statusCode: res.statusCode,
          responseTimeMs: elapsedMs,
        });
      } catch (error) {
        console.error("Failed to record API usage:", error);
      }
    });

    next();
  });

  /**
   * Basic health endpoint.
   */
  app.get("/health", (req, res) => {
    res.status(200).json({
      status: "ok",
      service: "reconciliation-api",
    });
  });
  /**
   * GET /api/v1/runs
   *
   * Returns persisted reconciliation runs.
   *
   * The API exposes the existing database records rather than creating
   * a separate API-specific representation of reconciliation runs.
   */
  app.get("/api/v1/runs", async (req, res) => {
    try {
      const runs = await listReconciliationRuns();

      return res.status(200).json({
        runs,
      });
    } catch (error) {
      console.error("Failed to retrieve reconciliation runs:", error);

      return res.status(500).json({
        error: "Failed to retrieve reconciliation runs.",
        message: error.message,
      });
    }
  });
  /**
   * GET /api/v1/runs/:runId
   *
   * Returns a complete persisted reconciliation run together with
   * the evidence generated during that run.
   *
   * This provides a reviewer-friendly traceability view:
   *
   * run
   *   ├── raw records
   *   ├── canonical events
   *   ├── decisions
   *   ├── asset states
   *   ├── exceptions
   *   └── report artifacts
   */
  app.get("/api/v1/runs/:runId", async (req, res) => {
    try {
      const { runId } = req.params;

      const run = await getReconciliationRun(runId);

      if (!run) {
        return res.status(404).json({
          error: "Reconciliation run not found.",
        });
      }

      const [
        rawRecords,
        canonicalEvents,
        decisions,
        assetStates,
        exceptions,
        reportArtifacts,
      ] = await Promise.all([
        getRawRecords(runId),
        getCanonicalEvents(runId),
        getEventDecisions(runId),
        getAssetStates(runId),
        getExceptionCases(runId),
        getReportArtifacts(runId),
      ]);

      return res.status(200).json({
        run,
        evidence: {
          rawRecords,
          canonicalEvents,
          decisions,
          assetStates,
          exceptions,
          reportArtifacts,
        },
      });
    } catch (error) {
      console.error("Failed to retrieve reconciliation run:", error);

      return res.status(500).json({
        error: "Failed to retrieve reconciliation run.",
        message: error.message,
      });
    }
  });
  /**
   * GET /api/v1/exceptions
   *
   * Returns persisted exception cases requiring attention.
   *
   * The endpoint reads directly from the persistence layer so that
   * operators see the same exception evidence generated by reconciliation.
   */
  app.get("/api/v1/exceptions", async (req, res) => {
    try {
      const exceptions = await listExceptionCases();

      return res.status(200).json({
        exceptions,
      });
    } catch (error) {
      console.error("Failed to retrieve exceptions:", error);

      return res.status(500).json({
        error: "Failed to retrieve exceptions.",
        message: error.message,
      });
    }
  });
  /**
   * POST /api/v1/exceptions/:caseId/resolve
   *
   * Resolves an open exception and records the resolution actor,
   * timestamp, and resolution message for auditability.
   *
   * Expected request body:
   *
   * {
   *   "resolvedBy": "admin-001",
   *   "resolution": "Reviewed and approved correction."
   * }
   */
  app.post("/api/v1/exceptions/:caseId/resolve", async (req, res) => {
    try {
      const { caseId } = req.params;
      const { resolvedBy, actorRole, resolution } = req.body ?? {};

      // All fields are required for an auditable resolution.
      if (!resolvedBy || !actorRole || !resolution) {
        return res.status(400).json({
          error: "resolvedBy, actorRole, and resolution are required.",
        });
      }

      // Only authorized operational roles may resolve exceptions.
      if (!canResolveException(actorRole)) {
        return res.status(403).json({
          error: "Actor role is not authorized to resolve exceptions.",
        });
      }

      // Resolve the exception in the persistence layer.
      const resolvedException = await resolveExceptionCase({
        caseId,
        resolvedBy,
        resolvedAt: new Date().toISOString(),
        resolution,
      });

      // The case does not exist.
      if (!resolvedException) {
        return res.status(404).json({
          error: "Exception case not found.",
        });
      }

      // Return the persisted resolution.
      return res.status(200).json({
        status: "resolved",
        exception: resolvedException,
      });
    } catch (error) {
      console.error("Failed to resolve exception:", error);

      return res.status(500).json({
        error: "Failed to resolve exception.",
        message: error.message,
      });
    }
  });
  /**
   * GET /api/v1/assets/:assetId
   *
   * Returns the current authoritative state of an asset together
   * with its recent canonical event history.
   */
  app.get("/api/v1/assets/:assetId", async (req, res) => {
    try {
      const { assetId } = req.params;

      if (!assetId) {
        return res.status(400).json({
          error: "Asset ID is required.",
        });
      }

      const assetState = await getCurrentAssetState(assetId);

      if (!assetState) {
        return res.status(404).json({
          error: "Asset not found.",
          assetId,
        });
      }

      const history = await getAssetEventHistory(assetId);

      return res.status(200).json({
        asset: assetState,
        history,
      });
    } catch (error) {
      console.error("Failed to retrieve asset:", error);

      return res.status(500).json({
        error: "Failed to retrieve asset.",
        message: error.message,
      });
    }
  });
  /**
   * POST /api/v1/webhooks
   *
   * Registers a webhook destination and its trigger filters.
   */
  app.post("/api/v1/webhooks", async (req, res) => {
    try {
      const { url, eventTypes = [], severities = [] } = req.body ?? {};

      if (!url || typeof url !== "string") {
        return res.status(400).json({
          error: "Webhook URL is required.",
        });
      }

      if (!Array.isArray(eventTypes) || !Array.isArray(severities)) {
        return res.status(400).json({
          error: "eventTypes and severities must be arrays.",
        });
      }

      const webhook = await registerWebhook({
        url,
        eventTypes,
        severities,
      });

      return res.status(201).json({
        status: "registered",
        webhook: {
          webhookId: webhook.webhook_id,
          url: webhook.url,
          eventTypes: webhook.event_types,
          severities: webhook.severities,
          active: webhook.active,
          createdAt: webhook.created_at,
        },
      });
    } catch (error) {
      console.error("Webhook registration failed:", error);

      return res.status(500).json({
        error: "Failed to register webhook.",
        message: error.message,
      });
    }
  });
  /**
   * POST /api/v1/events
   *
   * Accepts either:
   *
   * {
   *   "events": [...]
   * }
   *
   * or a single event object.
   *
   * The endpoint uses the existing validation, canonicalization,
   * deterministic ordering, and reconciliation pipeline.
   */
  app.post("/api/v1/events", async (req, res) => {
    try {
      if (!policy) {
        return res.status(500).json({
          error: "API policy is not configured.",
        });
      }

      let events;

      // Support a batch request.
      if (Array.isArray(req.body?.events)) {
        events = req.body.events;
      }
      // Also support a single event.
      else if (req.body && typeof req.body === "object") {
        events = [req.body];
      } else {
        return res.status(400).json({
          error: "Request body must contain an event or an events array.",
        });
      }

      if (events.length === 0) {
        return res.status(400).json({
          error: "At least one event is required.",
        });
      }
      const idempotencyKey = req.get("Idempotency-Key");

      if (!idempotencyKey) {
        return res.status(400).json({
          error: "Idempotency-Key header is required.",
        });
      }

      const existingEvent =
        await getCanonicalEventByIdempotencyKey(idempotencyKey);

      if (existingEvent) {
        return res.status(200).json({
          status: "duplicate",
          idempotent: true,
          canonicalEventIds: [existingEvent.canonical_event_id],
          runId: existingEvent.run_id,
        });
      }
      const result = processApiEvents({
        events,
        inventoryRawRecords,
        policy,
      });
      const exceptionQueue = buildExceptionQueue(
        result.reconciliationResult.decisions,
      );

      const autoResolutionResult = applyAutoResolution(exceptionQueue, policy);
      const persistence = await persistApiEventResult({
        events,
        rawRecords: result.rawRecords,
        canonicalEvents: result.canonicalEvents,
        reconciliationResult: result.reconciliationResult,
        policy,
        idempotencyKey,
        validationErrors: result.validationErrors,
        exceptionQueue: autoResolutionResult.exceptions,
        autoResolvedExceptions: autoResolutionResult.autoResolved,
      });
      for (const decision of result.reconciliationResult.decisions) {
        if (
          decision.decision === "REJECTED" ||
          decision.decision === "REVIEW_REQUIRED" ||
          decision.decision === "WARNING_ONLY" ||
          decision.decision === "ACCEPTED_WITH_WARNING"
        ) {
          await dispatchToMatchingWebhooks({
            eventType: decision.eventType,
            severity: decision.decision === "REJECTED" ? "ERROR" : "WARNING",
            runId: persistence.runId,
            eventId: decision.eventId,
            payload: {
              eventId: decision.eventId,
              eventType: decision.eventType,
              assetId: decision.assetId,
              decision: decision.decision,
              reasonCode: decision.reasonCode,
              message: decision.message,
              previousState: decision.previousState,
              nextState: decision.nextState,
            },
          });
        }
      }
      return res.status(200).json({
        status: "processed",
        runId: persistence.runId,
        canonicalEventIds: result.canonicalEvents.map(
          (event) => event.canonicalEventId,
        ),

        validation: {
          errors: result.validationErrors.filter(
            (error) => error.severity === "ERROR",
          ).length,

          warnings: result.validationErrors.filter(
            (error) => error.severity === "WARNING",
          ).length,
        },

        decisions: result.reconciliationResult.decisions.map((decision) => ({
          eventId: decision.eventId,
          assetId: decision.assetId,
          decision: decision.decision,
          reasonCode: decision.reasonCode,
          message: decision.message,
        })),

        summary: result.reconciliationResult.summary,
      });
    } catch (error) {
      console.error("API event processing failed:", error);

      return res.status(500).json({
        error: "Failed to process events.",
        message: error.message,
      });
    }
  });

  return app;
}

/**
 * Starts the API server.
 *
 * The port can be supplied through the environment or defaults to 3000.
 */
export function startApiServer(
  { inventoryRawRecords = [], policy = null } = {},
  port = process.env.PORT || 3000,
) {
  const app = createApiServer({
    inventoryRawRecords,
    policy,
  });

  return app.listen(port, () => {
    console.log(`Reconciliation API listening on port ${port}`);
  });
}
